import { clientSrcTemplatesBlock } from 'generator-jhipster/generators/client/support';

export const commonFiles = {
  layoutFiles: [
    // 同名同路径下的文件会自动覆盖
    clientSrcTemplatesBlock({
      transform: false,
      relativePath: 'content/images/',
      templates: [
        'avatar/amyelsner.png',
        'avatar/avatar-f-4.png',
        'avatar/avatar-f-8.png',
        'avatar/avatar-m-8.png',
        'logo.png',
        'logo.png',
        'chamera1-512.png',
      ],
    }),
  ],
  common: [
    {
      ...clientSrcTemplatesBlock(),
      transform: false,
      templates: [
        'content/theme/theme-dark/amber/fonts/Inter-italic.var.woff2',
        'content/theme/theme-dark/amber/fonts/Inter-roman.var.woff2',
        'content/theme/theme-dark/amber/theme.css',
        'content/theme/theme-dark/blue/fonts/Inter-italic.var.woff2',
        'content/theme/theme-dark/blue/fonts/Inter-roman.var.woff2',
        'content/theme/theme-dark/blue/theme.css',
        'content/theme/theme-dark/cyan/fonts/Inter-italic.var.woff2',
        'content/theme/theme-dark/cyan/fonts/Inter-roman.var.woff2',
        'content/theme/theme-dark/cyan/theme.css',
        'content/theme/theme-dark/green/fonts/Inter-italic.var.woff2',
        'content/theme/theme-dark/green/fonts/Inter-roman.var.woff2',
        'content/theme/theme-dark/green/theme.css',
        'content/theme/theme-dark/indigo/fonts/Inter-italic.var.woff2',
        'content/theme/theme-dark/indigo/fonts/Inter-roman.var.woff2',
        'content/theme/theme-dark/indigo/theme.css',
        'content/theme/theme-dark/pink/fonts/Inter-italic.var.woff2',
        'content/theme/theme-dark/pink/fonts/Inter-roman.var.woff2',
        'content/theme/theme-dark/pink/theme.css',
        'content/theme/theme-dark/purple/fonts/Inter-italic.var.woff2',
        'content/theme/theme-dark/purple/fonts/Inter-roman.var.woff2',
        'content/theme/theme-dark/purple/theme.css',
        'content/theme/theme-dark/teal/fonts/Inter-italic.var.woff2',
        'content/theme/theme-dark/teal/fonts/Inter-roman.var.woff2',
        'content/theme/theme-dark/teal/theme.css',
        'content/theme/theme-light/amber/fonts/Inter-italic.var.woff2',
        'content/theme/theme-light/amber/fonts/Inter-roman.var.woff2',
        'content/theme/theme-light/amber/theme.css',
        'content/theme/theme-light/blue/fonts/Inter-italic.var.woff2',
        'content/theme/theme-light/blue/fonts/Inter-roman.var.woff2',
        'content/theme/theme-light/blue/theme.css',
        'content/theme/theme-light/cyan/fonts/Inter-italic.var.woff2',
        'content/theme/theme-light/cyan/fonts/Inter-roman.var.woff2',
        'content/theme/theme-light/cyan/theme.css',
        'content/theme/theme-light/green/fonts/Inter-italic.var.woff2',
        'content/theme/theme-light/green/fonts/Inter-roman.var.woff2',
        'content/theme/theme-light/green/theme.css',
        'content/theme/theme-light/indigo/fonts/Inter-italic.var.woff2',
        'content/theme/theme-light/indigo/fonts/Inter-roman.var.woff2',
        'content/theme/theme-light/indigo/theme.css',
        'content/theme/theme-light/pink/fonts/Inter-italic.var.woff2',
        'content/theme/theme-light/pink/fonts/Inter-roman.var.woff2',
        'content/theme/theme-light/pink/theme.css',
        'content/theme/theme-light/purple/fonts/Inter-italic.var.woff2',
        'content/theme/theme-light/purple/fonts/Inter-roman.var.woff2',
        'content/theme/theme-light/purple/theme.css',
        'content/theme/theme-light/teal/fonts/Inter-italic.var.woff2',
        'content/theme/theme-light/teal/fonts/Inter-roman.var.woff2',
        'content/theme/theme-light/teal/theme.css',
      ],
    },
  ],
};
