import { clientRootTemplatesBlock, clientApplicationTemplatesBlock } from 'generator-jhipster/generators/client/support';

export const files = {
  common: [
    clientRootTemplatesBlock({
      templates: ['package.json', 'postcss.config.js', 'tailwind.config.js', 'webpack/webpack.common.js', 'webpack/webpack.dev.js'],
    }),
  ],
  reactApp: [
    {
      ...clientApplicationTemplatesBlock(),
      // 要基于ejs模板生成测设置为true
      transform: true,
      templates: [
        'app.css',
        'app.tsx',
        'config/constants.ts',
        'config/notification-middleware.ts',
        'config/translation.ts',
        'entities/entities-menu-data.ts',
        'entities/reducers.ts',
        'entities/dict/dict.reducer.ts',
        'entities/admin/authority/authority.reducer.ts',
        'index.tsx',
        'modules/account/password/password.tsx',
        'modules/account/password-reset/finish/password-reset-finish.tsx',
        'modules/account/password-reset/init/password-reset-init.css',
        'modules/account/password-reset/init/password-reset-init.tsx',
        'modules/account/register/register.tsx',
        'modules/account/settings/settings.tsx',
        'modules/administration/configuration/configuration.tsx',
        'modules/administration/docs/docs.tsx',
        'modules/administration/health/health-modal.tsx',
        'modules/administration/health/health.tsx',
        'modules/administration/logs/logs.tsx',
        'modules/administration/metrics/cacheMetrics.tsx',
        'modules/administration/metrics/datasourceMetrics.tsx',
        'modules/administration/metrics/endpointsRequestsMetrics.tsx',
        'modules/administration/metrics/garbageCollectorMetrics.tsx',
        'modules/administration/metrics/httpRequestMetrics.tsx',
        'modules/administration/metrics/jvmMemory.tsx',
        'modules/administration/metrics/jvmThreads.tsx',
        'modules/administration/metrics/metrics.tsx',
        'modules/administration/metrics/systemMetrics.tsx',
        'modules/administration/metrics/thread-item.tsx',
        'modules/administration/metrics/threads-modal.tsx',
        'modules/administration/user-management/index.tsx',
        'modules/administration/user-management/user-management-detail.tsx',
        'modules/administration/user-management/user-management-update.tsx',
        'modules/administration/user-management/user-management.tsx',
        'modules/dashboard/chart/bar.tsx',
        'modules/dashboard/chart/line.tsx',
        'modules/dashboard/chart/pie.tsx',
        'modules/dashboard/e-commerce.tsx',
        'modules/home/home.css',
        'modules/home/home.tsx',
        'modules/login/login-modal.tsx',
        'modules/login/login.css',
        'modules/login/login.tsx',
        'modules/login/logout.tsx',
        'routes.tsx',
        'shared/layout/bg.tsx',
        'shared/layout/full-page-layout.tsx',
        'shared/layout/header/header-components.tsx',
        'shared/layout/header/header.css',
        'shared/layout/header/header.tsx',
        'shared/layout/header/my-profile.css',
        'shared/layout/header/my-profile.tsx',
        'shared/layout/logo.tsx',
        'shared/layout/menus/bread-item.tsx',
        'shared/layout/menus/locale-dropdown.tsx',
        'shared/layout/menus/side-menu.tsx',
        'shared/layout/menus/sidebar.css',
        'shared/layout/menus/sidebar.tsx',
        'shared/layout/theme/theme-context.tsx',
        'shared/layout/theme/theme-selector.css',
        'shared/layout/theme/theme-selector.tsx',
        'shared/layout/theme/toast-manager.ts',
        'shared/layout/theme/use-theme.ts',
        'shared/model/dict.model.ts',
        'shared/model/admin/authority.model.ts',
        'shared/reducers/index.ts',
        'shared/reducers/ui.ts',
        'shared/util/entity-utils.ts',
        'shared/util/lxm-utils.tsx',
      ],
    },
  ],
};

export const unwantedFiles = {
  files: ['app/app.scss', 'app/modules/administration/user-management/user-management-delete-dialog.tsx'],
  entityFiles: ['app/entities/_entityFolder_/_entityFile_-delete-dialog.tsx'],
};
